name: iosApp
options:
  bundleIdPrefix: com.barter
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "26.0"

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.barter.ios
        PRODUCT_NAME: Barter
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: B49B4ZD6WL
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
        OTHER_LINKER_FLAGS:
          - "$(inherited)"
          - "-framework"
          - "shared"
    preBuildScripts:
      - name: "Build Kotlin Framework"
        script: |
          cd "$SRCROOT/.."
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
